[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/reddit"
  to = "/.netlify/functions/reddit-proxy"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news-proxy"
  status = 200

[[redirects]]
  from = "/api/policy-watch"
  to = "/.netlify/functions/policy-watch"
  status = 200
